name: async_redux
description: A Redux version which is easy to learn, to use, to test, and has no boilerplate. Allows for both sync and async reducers. Tailored for Flutter.
version: 3.0.5
author: Marcelo Glasberg <marcglasberg@gmail.com>
homepage: https://github.com/marcglasberg/async_redux

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  logging: ^0.11.4
  path: ^1.6.4
  path_provider: ^1.4.4
  file: ^6.0.0-nullsafety.1
  weak_map: ^1.3.1
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.6.3
  async: ^2.4.1
  flutter_test:
    sdk: flutter

flutter:

